#include "Game.h"

// TODO: ADICIONAR SONS PANDORAS BOX

// TODO: CHECAR PROMOTION E ATAQUE NO MESMO TURNO, E EM PEÇAS PRETAS
// TODO: CONSERTAR CASTLING (CHECAR CHECK NAS POSIÇÕES INTERMEDIÁRIAS, PROVAVELMENTE SERIA BOM FAZER UMA FUNÇÃO
// QUE CHEQUE O CHECK NUM BOARD GENÉRICO)

int main() {
    Game().Run();

    return 0;
}